const TEMPLATE = {
    SELECT: "TEMPLATE_SELECT",
    DOWNLOAD: "TEMPLATE_DOWNLOAD",
    DOWNLOAD_SUCCESSFUL: "TEMPLATE_DOWNLOAD_SUCCESSFUL",
    DOWNLOAD_FAILED: "TEMPLATE_DOWNLOAD_FAILED"
}

const PHASE = {
    CURRENT: "PHASE_CURRENT",
    NEXT: 'PHASE_NEXT',
    PREVIOUS: 'PHASE_PREVIOUS'
}

const FORM = {
    SUBMIT: "FORM_SUBMIT",
    SUBMIT_SUCCESSFUL: "FORM_SUBMIT_SUCCESSFUL",
    SUBMIT_LOADING: "FORM_SUBMIT_LOADING",
    SUBMIT_FAILED: "FORM_SUBMIT_FAILED"
}

export {TEMPLATE, PHASE, FORM}